version: "3.8"

services:

  workspace:
    image: mcr.microsoft.com/devcontainers/python:3.11
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
